### ISSUE TITLE
不错的方案

### ISSUE THREAD

**Issue by unbrraise** [kingpy2125/CampusNetwork#1]
珠海科技学院有不用刷固件的方案咩

**Comment by ChanMing9086** [comment]
没有

unbrraise ***@***.***> 于 2024年10月8日周二 00:10写道：

**Comment by ChanMing9086** [comment]
学校是网页认证，一定要路由器才可以

ChanMing Ting ***@***.***> 于 2024年10月9日周三 10:32写道：

**Comment by unbrraise** [comment]
我有一个老账号，可以使用路由器登录，但是试了一下新办理宽带账号，路由器是登陆不了的，校园网是不让路由器登录吗

**Comment by ChanMing9086** [comment]
你描述的我不太明白，是用路由器拨号吗


unbrraise ***@***.***> 于2024年10月24日周四 14:21写道：

**Comment by unbrraise** [comment]
没错

**Comment by ChanMing9086** [comment]
路由器用DHCP就可以，网页认证
